spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      uri: http://localhost:50100
      request-connect-timeout: 5000 #ms
      request-read-timeout: 5000 #ms
      fail-fast: false

logging:
  level:
    root: DEBUG
    org.springframework.security: TRACE

