spring:
  cloud:
    config:
      enabled: false
  data:
    redis:
      host: polar-redis
      port: 6379
logging:
  level:
    tech.jhipster: DEBUG
    reactor.netty: INFO
    io.github.resilience4j: DEBUG
    root: INFO
    
    
CATALOG_SERVICE_URL:  http://catalog-service
ORDER_SERVICE_URL: http://order-service
AUTH_SERVER_URL: http://polar-keycloak
SPA_URL: http://polar-ui