apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: ghcr.io/ubaid4j/edge-service:0.0.3-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50090
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 50090
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 50090
            initialDelaySeconds: 5
            periodSeconds: 15
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service
            - name: ORDER_SERVICE_URL
              value: http://order-service
            - name: SPRING_DATA_REDIS_HOST
              value: polar-redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "1"
            - name: AUTH_SERVER_URL
              value: "http://polar-keycloak"
            - name: SPA_URL
              value: http://polar-ui
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: "DEBUG"

          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
